version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: redditlike
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data